// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PhotoMetadata = { filename: string, full_path: string, filesize: bigint, rating: number, is_picked: boolean, };
